# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example_protos/example.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='example_protos/example.proto',
  package='example.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1c\x65xample_protos/example.proto\x12\nexample.v1\"-\n\x07Request\x12\t\n\x01\x41\x18\x01 \x01(\x05\x12\t\n\x01\x42\x18\x02 \x01(\x05\x12\x0c\n\x04Type\x18\x03 \x01(\t\"9\n\x08Response\x12-\n\x06Result\x18\x01 \x01(\x0b\x32\x1d.example.v1.DataResponseField\"\"\n\x11\x44\x61taResponseField\x12\r\n\x05Value\x18\x01 \x01(\x02\x32\x46\n\x0e\x45xampleService\x12\x34\n\x07GetData\x12\x13.example.v1.Request\x1a\x14.example.v1.Responseb\x06proto3')
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='example.v1.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='A', full_name='example.v1.Request.A', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='B', full_name='example.v1.Request.B', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Type', full_name='example.v1.Request.Type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=89,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='example.v1.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Result', full_name='example.v1.Response.Result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=148,
)


_DATARESPONSEFIELD = _descriptor.Descriptor(
  name='DataResponseField',
  full_name='example.v1.DataResponseField',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Value', full_name='example.v1.DataResponseField.Value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=184,
)

_RESPONSE.fields_by_name['Result'].message_type = _DATARESPONSEFIELD
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['DataResponseField'] = _DATARESPONSEFIELD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'example_protos.example_pb2'
  # @@protoc_insertion_point(class_scope:example.v1.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'example_protos.example_pb2'
  # @@protoc_insertion_point(class_scope:example.v1.Response)
  })
_sym_db.RegisterMessage(Response)

DataResponseField = _reflection.GeneratedProtocolMessageType('DataResponseField', (_message.Message,), {
  'DESCRIPTOR' : _DATARESPONSEFIELD,
  '__module__' : 'example_protos.example_pb2'
  # @@protoc_insertion_point(class_scope:example.v1.DataResponseField)
  })
_sym_db.RegisterMessage(DataResponseField)



_EXAMPLESERVICE = _descriptor.ServiceDescriptor(
  name='ExampleService',
  full_name='example.v1.ExampleService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=186,
  serialized_end=256,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetData',
    full_name='example.v1.ExampleService.GetData',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXAMPLESERVICE)

DESCRIPTOR.services_by_name['ExampleService'] = _EXAMPLESERVICE

# @@protoc_insertion_point(module_scope)
